server:
  port: 8085
logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.trustteam.cnbees: DEBUG

spring:
  profiles:
    active: 'dev'
  application:
    name: 'Crowdfunding'
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true